---
- name: Install Docker on Debian / Raspberry Pi OS
  hosts: all
  gather_facts: true
  become: true
  tasks:

    - name: Remove all packages that can be problematic
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
         - docker.io
         - docker-doc
         - docker-compose
         - podman-docker
         - containerd
         - runc

    - name: apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Creating /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'armhf' }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: Update apt and install Docker
      ansible.builtin.apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
