---
- name: Installing vim & it's playbook
  hosts: all
  become: true

  tasks:
    - name: Installer les paquets nécessaires
      ansible.builtin.apt:
        name:
          - vim
          - curl
          - git
        state: present
        update_cache: yes

    - name: Créer le répertoire .vim si nécessaire
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.vim"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: false

    - name: Créer le répertoire autoload
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.vim/autoload/"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: false

    - name: Télécharger vim-plug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "/home/{{ ansible_user }}/.vim/autoload/plug.vim"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Créer le fichier de configuration .vimrc
      ansible.builtin.copy:
        dest: "/home/{{ansible_user}}/.vimrc"
        content: |
          call plug#begin('~/.vim/plugged')

          " Liste des plugins Vim
          Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " Fuzzy finder
          Plug 'tpope/vim-fugitive'        " Intégration Git

          call plug#end()

          syntax on
          set number
          set autoread

          augroup filetype_specific_tab
            autocmd!
            autocmd FileType python set tabstop=4 shiftwidth=4 expandtab
            autocmd FileType yaml set tabstop=2 shiftwidth=2 expandtab
          augroup END
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Installer les plugins Vim
      become: false
      command: vim +PlugInstall +qall
      args:
        creates: "/home/{{ ansible_user }}/.vim/plugged"
      environment:
        HOME: "/home/{{ ansible_user }}"

